name: Build ollama image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: "${{ secrets.HARBOR_IP }}"
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push
      uses: docker/build-push-action@v3

      with:
        context: ./dockerfiles/ollama
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads/cads-ollama:${{ github.event.inputs.image_tag }}
        file: ./dockerfiles/ollama/Dockerfile
