name: Build search image

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Deployment branch'
        required: true
        default: 'main'
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to harbor registry
      uses: docker/login-action@v2
      with:
        registry: "${{ secrets.HARBOR_IP }}"
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_TOKEN }}
    - name: Setup docker context for buildx
      id: buildx-context
      run: docker context create builders || docker context use builders

    - name: Create BuildKit Configuration
      run: |
        cat <<EOF > buildkitd.toml
        [registry."${{ secrets.HARBOR_IP }}"]
          http = false
          insecure = false
          ca=["/etc/ssl/certs/ca-certificates.crt"]
        EOF
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
        endpoint: builders
        buildkitd-flags: --debug
        config: buildkitd.toml

    - name: Checkout cads-search repo
      uses: actions/checkout@v3
      with:
        repository: ecmwf/cads-search
        ref: ${{ github.event.inputs.deployment_branch }}
        token: ${{ secrets.CADS_PAT }}
        path: .

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.HARBOR_IP }}/cads/cads-search:${{ github.event.inputs.image_tag }}
        file: Dockerfile
