name: 'Docker build tag and push'
description: 'Docker build tag and push on a container registry'

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string

jobs:
  building-docker-image:
    runs-on:
      - ubuntu-latest
    steps:

      - name: Checkout code-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout cads-build-farm
        uses: actions/checkout@v4
        with:
          repository: ecmwf-projects/cads-build-farm
          path: cads-build-farm
          ref: helm-chart-pipeline

      - name: Copy all shared scripts to root
        run: cp cads-build-farm/scripts/* ./

      - name: compute semantic version
        uses: ecmwf-projects/cads-build-farm/.github/actions/git-version@helm-chart-pipeline
        id: version

      - name: Debug registry secrets
        run: |
          echo "HARBOR_USER is set? -> ${{ secrets.HARBOR_USER != '' }}"
          echo "HARBOR_TOKEN is set? -> ${{ secrets.HARBOR_TOKEN != '' }}"

      - name: Debug - Check if secrets are set (caller)
        run: |
          echo "::add-mask::${{ secrets.HARBOR_USER }}"
          echo "::add-mask::${{ secrets.HARBOR_TOKEN }}"



      - name: Login to harbor registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_IP }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}


      - uses: ecmwf-projects/cads-build-farm/.github/actions/image-variables@helm-chart-pipeline
        id: image-variables

      - name: Dockerfile build tag and push
        uses: ecmwf-projects/cads-build-farm/.github/actions/docker-build@helm-chart-pipeline
        with:
          registry: ${{ secrets.HARBOR_IP }}
          dockerfile: ${{ inputs.dockerfile }}
          base-image-tag: ${{ steps.version.outputs.version }}
          base-image-name: ${{ steps.image-variables.outputs.build-image-name }}
          image-tag: ${{ steps.image-variables.outputs.image-name }}:${{ steps.version.outputs.version }}
