name: Build worker-scheduler chart

on: []



jobs:
  build_helm_chart:
    name: Build helm chart:${{ inputs.image_tag }} from ${{ inputs.build_mode }}
    uses: ecmwf-projects/cads-build-farm/.github/workflows/helm-chart.yaml@main
    with:
      helmFolder: helm_output
      build_mode: ${{ inputs.build_mode }}
      image_tag: ${{ inputs.image_tag }}
      registryUrl: ${{ secrets.HARBOR_IP }}
      registryUsername: ${{ secrets.HARBOR_USER }}
      registryPassword: ${{ secrets.HARBOR_TOKEN }}
    secrets: inherit

