name: 'Helm build tag and push'
description: 'Package an Helm Chart and push on a container registry'

on:
  workflow_call:
    inputs:
      helmFolder:
        type: string
        default: ""
        required: true
      # registryUrl:
      #   type: string
      #   default: ""
      #   required: true
      # registryUsername:
      #   type: string
      #   default: ""
      #   required: true
      # registryPassword:
      #   type: string
      #   default: ""
      #   required: true

env:
    registryUrl: https://eccr.ecmwf.int/chartrepo/polytope
    registryUsername: ${{ secrets.ECMWF_DOCKER_REGISTRY_USERNAME }}
    registryPassword: ${{ secrets.ECMWF_DOCKER_REGISTRY_ACCESS_TOKEN }}


jobs:
  building-helm-chart:
    runs-on:
      - ubuntu-latest
    steps:

      - name: Checkout cads-deployment repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to harbor registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registryUrl }}
          username: ${{ env.registryUsername }}
          password: ${{ env.registryPassword }}

      - name: Set Helm Chart Variables
        shell: bash
        id: set_vars
        run: |
          cd ./helmchart/worker-schedulers
          chartName=$(awk '/^name:/{print $2}' Chart.yaml)
          chartVersion=$(awk '/^version:/{print $2}' Chart.yaml)

          echo "HELM_CHART_NAME=$chartName" >> $GITHUB_ENV
          echo "HELM_CHART_VERSION=$chartVersion" >> $GITHUB_ENV
        working-directory: ${{ inputs.helmFolder }}

      - name: helm build and push
        shell: bash
        run: |
          docker run \
          --rm \
          --entrypoint=sh \
          -v $(pwd)/${{ inputs.helmFolder }}:/work \
          -w /work alpine/helm \
          -c "helm registry login ${{ inputs.registryUrl }} --username ${{ inputs.registryUsername }} --password ${{ inputs.registryPassword }} && helm package . && helm push /work/$ELM_CHART_NAME-ELM_CHART_VERSION.tgz oci://${{ inputs.registryUrl }}/cads"