name: Build worker-scheduler chart

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Deployment branch'
        required: true
        default: 'main'
    types: [requested]

jobs:
  build_helm_chart:
    name: Build helm chart
    uses: ecmwf-projects/cads-build-farm/.github/workflows/helm-chart.yaml@main
    with:
      helmFolder: helm_output
      build_mode: ${{ inputs.build_mode }}
      registryUrl: ${{ secrets.HARBOR_IP }}
      registryUsername: ${{ secrets.HARBOR_USER }}
      registryPassword: ${{ secrets.HARBOR_TOKEN }}
    secrets: inherit

